apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
  labels:
    app: nginx-statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: default # {"$ref":"#/definitions/io.k8s.cli.setters.namespace"}
spec:
  selector:
    matchLabels:
      app: nginx-statefulset
  serviceName: "nginx"
  replicas: 2 # {"$ref":"#/definitions/io.k8s.cli.setters.sts-replicas"}
  template:
    metadata:
      labels:
        app: nginx-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.11
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
